//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyExpenseDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorExpense
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string String { get; set; }
    }
}
