//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyExpenseDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripExpense
    {
        public int Id { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> FriendId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ExpenseOnId { get; set; }
        public string Descriptions { get; set; }
        public string Dates { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
